version: "3"
services:
  my-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - /.env
    depends_on:
      - mongo
    networks:
      - myNet
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: siam
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - db_data:/app/data/db
    networks:
      - myNet

networks:
  myNet:
    driver: bridge

volumes:
  db_data:
    driver: local
