version: "3"
services:
  my-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NAME=DEV ENV
    command: npm run dev
# volumes:
#   app_data:
#     driver: local
